spring:
  application:
    name: fraud-detection-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  kafka:
    bootstrap-servers: ${KAFKA_HOST}:${KAFKA_PORT}

    consumer:
      group-id: fraud-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false
            value:
              default:
                type: java.util.HashMap

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8083

account:
  service:
    url: http://${ACCOUNT_SERVICE_HOST}:${ACCOUNT_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info

fraud:
  max-transaction-per-minute: 2
  suspicious-amount-multiplier: 5
  max-balance-percentage: 90
